<?php

return [
    [
        'id' => 1,
        'title' => 'Premium Corner Plot',
        'city' => 'Jaipur',
        'type' => 'Plot',
        'area_sqft' => 1450,
        'deal_value' => '68 Lakhs',
        'completion_year' => 2023,
        'image_url' => 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&q=80',
        'description' => 'A beautiful corner plot in one of Jaipur\'s most sought-after JDA approved localities.',
    ],
    [
        'id' => 2,
        'title' => 'Prime Office Space, Thane',
        'city' => 'Mumbai',
        'type' => 'Commercial Space',
        'area_sqft' => 2200,
        'deal_value' => 'Lease',
        'completion_year' => 2023,
        'image_url' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&q=80',
        'description' => 'Secured a long-term lease for a corporate client in a prime IT park.',
    ],
    [
        'id' => 3,
        'title' => 'Heritage Premium Villa',
        'city' => 'Ajmer',
        'type' => 'Villa',
        'area_sqft' => 4000,
        'deal_value' => '2.5 Cr',
        'completion_year' => 2024,
        'image_url' => 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600&q=80',
        'description' => 'Exclusive 4000 sqft property with modern amenities near Anasagar Lake.',
    ],
    [
        'id' => 4,
        'title' => 'Commercial Complex Plot',
        'city' => 'Kota',
        'type' => 'Commercial Space',
        'area_sqft' => 1800,
        'deal_value' => '85 Lakhs',
        'completion_year' => 2022,
        'image_url' => 'https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=600&q=80&fit=crop&auto=format',
        'description' => 'Spacious commercial plot located near top educational institutes.',
    ],
    [
        'id' => 5,
        'title' => 'Retail Shop in High Street',
        'city' => 'Jaipur',
        'type' => 'Commercial Space',
        'area_sqft' => 800,
        'deal_value' => '1.2 Cr',
        'completion_year' => 2023,
        'image_url' => 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600&q=80',
        'description' => 'High footfall retail space closed for a renowned franchise brand.',
    ],
    [
        'id' => 6,
        'title' => 'Residential Plot, Ajmer Road',
        'city' => 'Jaipur',
        'type' => 'Plot',
        'area_sqft' => 2500,
        'deal_value' => '45 Lakhs',
        'completion_year' => 2021,
        'image_url' => 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&q=80',
        'description' => 'Premium plot in a gated township, perfect for building a custom villa.',
    ],
    [
        'id' => 7,
        'title' => 'Luxury Villa, Bandra',
        'city' => 'Mumbai',
        'type' => 'Villa',
        'area_sqft' => 3100,
        'deal_value' => '4.8 Cr',
        'completion_year' => 2024,
        'image_url' => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80',
        'description' => 'A luxury villa with stunning Arabian Sea views.',
    ],
    [
        'id' => 8,
        'title' => 'Student Hostel Building',
        'city' => 'Kota',
        'type' => 'Commercial Space',
        'area_sqft' => 5500,
        'deal_value' => '3.2 Cr',
        'completion_year' => 2023,
        'image_url' => 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600&q=80',
        'description' => 'High ROI commercial property catering to the student population.',
    ]
];
